use resx_ffi::analysis::codec;
use std::path::PathBuf;

#[test]
#[ignore = "requires RESX_CODEC_ORACLE generated by the offline Python oracle"]
fn independent_compressor_vectors_and_mutations() {
    let root = PathBuf::from(std::env::var_os("RESX_CODEC_ORACLE").expect("RESX_CODEC_ORACLE"));
    let manifest: serde_json::Value =
        serde_json::from_slice(&std::fs::read(root.join("manifest.json")).unwrap()).unwrap();
    let mut passed = 0;
    for row in manifest["cases"].as_array().unwrap() {
        let name = row["name"].as_str().unwrap();
        let method = row["codec"].as_str().unwrap();
        let input = std::fs::read(root.join(format!("{name}.encoded"))).unwrap();
        let expected = std::fs::read(root.join(format!("{name}.expected"))).unwrap();
        let result = codec::decode(method, &input);
        if row["expected"] == "reject-budget" {
            assert!(result.unwrap_err().contains("budget"));
            continue;
        }
        assert_eq!(
            result.unwrap_or_else(|e| panic!("{name} {method}: {e}")),
            expected,
            "{name} {method}"
        );
        passed += 1;
        if matches!(method, "gzip" | "zlib") {
            for position in [0, input.len() / 2, input.len() - 1] {
                assert!(
                    codec::decode(method, &input[..position]).is_err(),
                    "truncated {name} {position}"
                );
            }
            let mut changed = input.clone();
            *changed.last_mut().unwrap() ^= 0x80;
            assert!(
                codec::decode(method, &changed).is_err(),
                "bad checksum {name}"
            );
        }
    }
    assert!(passed >= 200);
    assert!(
        codec::decode("zlib", &std::fs::read(root.join("bomb.zlib")).unwrap())
            .unwrap_err()
            .contains("budget")
    );
    println!("{passed} independent vectors decoded; framed truncation/checksum and expansion-budget controls passed");
}

#[test]
fn bounded_malformed_streams_never_panic() {
    let mut seed = 0x91324abcu64;
    for length in 0..256 {
        let bytes: Vec<_> = (0..length)
            .map(|_| {
                seed ^= seed << 13;
                seed ^= seed >> 7;
                seed ^= seed << 17;
                seed as u8
            })
            .collect();
        for method in ["deflate", "zlib", "gzip", "base64", "hex"] {
            let _ = codec::decode(method, &bytes);
        }
    }
}
