#![cfg(windows)]
use resx::analysis::{codec, crypto_decode};
use std::path::PathBuf;

#[test]
#[ignore = "requires RESX_AES_ORACLE generated by the local independent crypto library"]
fn cng_matches_independent_aes128_192_256_cbc_with_and_without_padding() {
    let root = PathBuf::from(std::env::var_os("RESX_AES_ORACLE").expect("RESX_AES_ORACLE"));
    let manifest: serde_json::Value =
        serde_json::from_slice(&std::fs::read(root.join("manifest.json")).unwrap()).unwrap();
    for row in manifest["cases"].as_array().unwrap() {
        let name = row["name"].as_str().unwrap();
        let key = std::fs::read(root.join(format!("{name}.key"))).unwrap();
        let encrypted = std::fs::read(root.join(format!("{name}.ciphertext"))).unwrap();
        let expected = std::fs::read(root.join(format!("{name}.expected"))).unwrap();
        let iv = codec::decode("hex", row["iv"].as_str().unwrap().as_bytes()).unwrap();
        assert_eq!(
            crypto_decode::aes_cbc(&encrypted, &key, &iv, row["padding"].as_bool().unwrap())
                .unwrap(),
            expected,
            "{name}"
        );
    }
}
